version: '3.8'

services:
  acoes:
    build: ../acoes
    ports:
      - "3003:3003"
    volumes:
      - ../acoes:/app
      - ../acoes/db:/app/db
    environment:
      - FLASK_DEBUG=0

  dolar:
    build: ../dolar
    ports:
      - "3004:3004"
    volumes:
      - ../dolar:/app
      - ../dolar/db:/app/db
    environment:
      - FLASK_DEBUG=0

  bitcoin:
    build: ../bitcoin
    ports:
      - "3005:3005"
    volumes:
      - ../bitcoin:/app
      - ../bitcoin/db:/app/db
    environment:
      - FLASK_DEBUG=0

  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL_ACOES=http://localhost:3003
      - REACT_APP_API_URL_DOLAR=http://localhost:3004
      - REACT_APP_API_URL_BITCOIN=http://localhost:3005
    depends_on:
      - acoes
      - dolar
      - bitcoin